// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXaRoBmbDJYFWM9E21_yBrC6QZUYO6AFQ',
    appId: '1:769497296566:web:4729a934392e82f9d14017',
    messagingSenderId: '769497296566',
    projectId: 'learning1-105f2',
    authDomain: 'learning1-105f2.firebaseapp.com',
    storageBucket: 'learning1-105f2.appspot.com',
    measurementId: 'G-RTPDR6QCZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-nk_MOAG9V7O4D_eBQO8w4ni6nUP6vyY',
    appId: '1:769497296566:android:ed12faf1c5a2be3cd14017',
    messagingSenderId: '769497296566',
    projectId: 'learning1-105f2',
    storageBucket: 'learning1-105f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqkcbLNWgTNMgRaEq0pbVhPPFllDe-Hps',
    appId: '1:769497296566:ios:0e263b31b5e10d4bd14017',
    messagingSenderId: '769497296566',
    projectId: 'learning1-105f2',
    storageBucket: 'learning1-105f2.appspot.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqkcbLNWgTNMgRaEq0pbVhPPFllDe-Hps',
    appId: '1:769497296566:ios:51a92d342fd00395d14017',
    messagingSenderId: '769497296566',
    projectId: 'learning1-105f2',
    storageBucket: 'learning1-105f2.appspot.com',
    iosBundleId: 'com.example.learningApp.RunnerTests',
  );
}
